# Generated by Django 5.0.6 on 2024-06-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suscripciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripciones',
            old_name='description',
            new_name='descripcion',
        ),
    ]
