# Generated by Django 5.0.6 on 2024-07-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_description_suscripciones_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripciones',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
