# Generated by Django 5.0.6 on 2024-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_suscripciones_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
