# Generated by Django 5.0.6 on 2024-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_revista_suscripcion_alter_suscripciones_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripciones',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='descripcion'),
        ),
    ]
